jobs:
  daprbot:
    name: bot-processor
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Comment analyzer
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.DAPR_BOT_TOKEN}}
        script: "const payload = context.payload;\nconst issue = context.issue;\n\
          const isFromPulls = !!payload.issue.pull_request;\nconst commentBody = payload.comment.body;\n\
          if (!isFromPulls && commentBody && commentBody.indexOf(\"/assign\") == 0)\
          \ {\n  if (!issue.assignees || issue.assignees.length === 0) {\n    await\
          \ github.rest.issues.addAssignees({\n      owner: issue.owner,\n      repo:\
          \ issue.repo,\n      issue_number: issue.number,\n      assignees: [context.actor],\n\
          \    })\n  }\n  return;\n}"
name: dapr-bot
on:
  repository_dispatch:
    types: trigger-ga___dapr-bot.yml
